name: tests

on:
  push:
    branches: [ "1.x" ]
  pull_request:
    branches: [ "1.x" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update --prefer-dist --no-progress --prefer-stable
    - name: Execute tests
      run: ./vendor/bin/phpunit
